# 서버 포트
server:
  port: 8080

# 어플리케이션 명
spring:
  application:
    name: 3o3

  # H2 Database Configuration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:szsdb
    username: szs
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 Console Configuration (Optional)
  h2:
    console:
      enabled: true
      path: /h2-console

# springdoc swagger configuration
springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /3o3/swagger-ui.html

# jwt secretKey
jwt:
  secret: szs1!szs2@